spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
    import: application-local.yml, application-swagger.yml, application-oauth.yml, application-mail.yml, application-s3.yml

---
spring:
  config:
    activate:
      on-profile: prod
    import: application-prod.yml, application-swagger.yml, application-oauth.yml, application-mail.yml, application-s3.yml
